### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by albertolo** [TwilioDevEd/ivr-phone-tree-csharp#4]
This example does not work , the documentation is wrong (for example the endpoint) , 
is there any working example with .net? 
![image](https://cloud.githubusercontent.com/assets/1964766/23132885/b5b73e3e-f754-11e6-83c8-7c37f3c9c283.png)

**Comment by acamino** [comment]
@albertolo, thanks for reporting this issue. I've applied the fix for the README file with the commit 673a69f.

Please, keep in mind that [`/ivr/welcome`](https://github.com/TwilioDevEd/ivr-phone-tree-csharp/blob/master/IVRPhoneTree.Web/Controllers/IVRController.cs#L15-L17) is a POST endpoint. To test this endpoint you might want to try the [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en) Chrome extension.

Another alternative is to use `curl`:

```
$ curl -XPOST http://localhost: 1112/ivr/welcome
```

Let me know if you have additional questions please.
